WebAppSISGEFIN/Controllers/ReportesController.cs
using General.Librerias.AccesoDatos;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppSISGEFIN.Models;

namespace WebAppSISGEFIN.Controllers
{
    public class ReportesController : Controller
    {

        [HttpGet]
        public string GetOficinas()
        {
            string _data = "M_OFICINA|OFI_SECUENCIA|OFI_ABREVIATURA|OFI_NOMBRE Like 'OFICINA%'";
            var _trama = Runs.GetTrama4Combo(_data);
            return _trama;
        }

        [HttpGet]
        public string GetUbicaciones()
        {
            string _data = "PATRI_UBICACION_FISICA|UBIFIS_SECUENCIA|UBIFIS_NOMBRE|";
            var _trama = Runs.GetTrama4Combo(_data);
            return _trama;
        }

        [HttpGet]
        public ActionResult ShowRpt(string area, string name, string type, string par, string r)
        {
            string _binDir = ConfigurationManager.AppSettings.Get("BinDir");
            string _dirRpt = string.Format("{0}\\{1}", _binDir, "filesRpt");
            ViewBag.FileNm = $"{_dirRpt}\\{area}{name}.rpt";
            ViewBag.SpName = $"usp{area}{name}ReporteCsv";
            ViewBag.Option = r;
            string _vName = "";
            if (par != null)
            {
                ViewBag.TypeNm = type;
                ViewBag.Params = par;
                _vName = "_PuenteRpt";
            }
            else
            {
                ViewBag.TypeNm = type;
                _vName = name;
            }
            return View(_vName);
        }

        public ActionResult MsgRpt(string msg, byte e)
        {
            rMensaje _mensj = new rMensaje();
            switch (e)
            {
                case 1:
                    _mensj.Type = "Informe";
                    _mensj.Image = "../../Images/rpt_info.png";
                    break;

                case 2:
                    _mensj.Type = "Alerta";
                    _mensj.Image = "../../Images/rpt_alert.png";
                    break;

                default:
                    _mensj.Type = "Error";
                    _mensj.Image = "../../Images/rpt_error.png";
                    break;
            }
            _mensj.Message = msg;
            return View("MsgRpt", _mensj);
        }

    }

}

WebAppSISGEFIN/Views/Reportes/Inventario1.cshtml
@{
    Layout = "_LayoutRpt.cshtml";
}

<input type="hidden" id="FileNm" value='@ViewBag.FileNm' />
<input type="hidden" id="SpName" value='@ViewBag.SpName' />
<input type="hidden" id="TypeNm" value='@ViewBag.TypeNm' />
<input type="hidden" id="Params" value='' />

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="flex-gap marco">

                <div>
                    <span>Año</span>
                    <input type="number" id="txtEjecucion" onchange="ActualizarSel()" class="form-control form-control-sm" min="2000" max="2100" value="2022" />
                </div>

                <div>
                    <span>Oficinas</span>
                    <select id="cboOficinas" onchange="ActualizarSel()" class="form-control form-control-sm"></select>
                </div>

                <div>
                    <span>Ubicación</span>
                    <select id="cboUbicaciones" onchange="ActualizarSel()" class="form-control form-control-sm"></select>
                </div>

                <div>
                    <span>Responsable</span>
                    <input type="number" id="txtResponsable" onchange="ActualizarSel()" class="form-control form-control-sm" />
                </div>

                <div>
                    <span>Usuario</span>
                    <input type="number" id="txtUsuario" onchange="ActualizarSel()" class="form-control form-control-sm" />
                </div>

                <div style="flex-direction: column;">

                    <table class="table table-sm" style="font-size:12px;" >
                        <tr>
                            <td>
                               <label for="option1">CR</label>
                            </td>
                            <td>
                                <input type="radio" id="option1" name="options" style="height: 15px;" checked class="form-control form-control-sm" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="option2">PDF</label>
                            </td>
                            <td>
                                <input type="radio" id="option2" name="options" style="height: 15px;" class="form-control form-control-sm" />
                            </td>
                        </tr>
                    </table>

                </div>

                <div>
                    <input type="button" class="btn btn-sm btn-primary" value="Consultar" onclick="ConsultarSel()" />
                </div>

            </div>             

            <div>
                <iframe id="iFrame" src="about://blank" frameborder="0"></iframe>
            </div>
            

        </div>
    </div>
</div>

<script>

    function ConsultarSel() {
        mostrarProgreso('Consultando..');

        const _iFrame = document.getElementById("iFrame");

        const _FileNm = document.getElementById("FileNm").value;
        const _SpName = document.getElementById("SpName").value;
        const _TypeNm = document.getElementById("TypeNm").value;
        const _Params = document.getElementById("Params").value;
        const _Option = document.getElementById("option1").checked ? 1 : 2;
        debugger
        const _UrlDoc = `/rptViewer.aspx?FileNm=${_FileNm}&SpName=${_SpName}&TypeNm=${_TypeNm}&Params=${_Params}&r=${_Option}`;

        _iFrame.onload = function () {
            _iFrame.contentDocument.body.style = "margin: 0px !Important; overflow:hidden !Important; ";
            _iFrame.contentDocument.cookie = "";
            _iFrame.style.display = "block";
            ocultarProgreso();
        }
        _iFrame.src = _UrlDoc;

    };

    function ActualizarSel() {
        const _txtEjecucio = document.getElementById('txtEjecucion');
        const _cboOficinas = document.getElementById('cboOficinas');
        const _cboUbicacns = document.getElementById('cboUbicaciones');
        const _txtRespons = document.getElementById('txtResponsable');
        const _txtUsuario = document.getElementById('txtUsuario');
        const _Params = document.getElementById('Params');
        _Params.value = _txtEjecucio.value;
        _Params.value += '|' + _cboOficinas.value;
        _Params.value += '|' + _cboUbicacns.value;
        _Params.value += '|' + _txtRespons.value;
        _Params.value += '|' + _txtUsuario.value;
    }

    async function CargarCombo(nombre) {

        const _cboName = 'cbo' + nombre;
        const _actName = 'Get' + nombre;

        var _data = sessionStorage.getItem(_cboName);

        if (_data == null) {
            const _auxUrl = '@Url.Action("X","Reportes")';
            const _newUrl = _auxUrl.replace('X', _actName);
            const response = await fetch(_newUrl);
            _data = await response.text();
            sessionStorage.setItem(_cboName, _data);
        }

        var _lista = _data.split('¬');
        crearCombo(_lista, _cboName, "")

    }

    window.onload = async function ()
    {
        await CargarCombo('Oficinas');
        await CargarCombo('Ubicaciones');
        ActualizarSel();
    }

</script>

WebAppSISGEFIN/Views/Reportes/MsgRpt.cshtml
@model WebAppSISGEFIN.Models.rMensaje
@{
    Layout = "_LayoutRpt.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row shadow-sm marco" style="margin-top:50px !important" >
                <div class="col-md-3">
                    <br />
                    <center>
                        <img src="@Model.Image" width="200px" height="225px" />
                    </center>
                </div>
                <div class="col-md-9" style="font-family: Tahoma; font-size: 20px; ">
                    <br />
                    <h3>
                        @Model.Type
                    </h3>
                    @Model.Message
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

WebAppSISGEFIN/Views/Reportes/PuenteRpt.cshtml
@{
    Layout = "_LayoutRpt.cshtml";
}

<style>
    #iFrame {
        position: absolute !important;
        left: 0px !important;
        top: 0px !important;
        width: 100% !important;
        height: 100vh !important;
        /*overflow: hidden;*/
    }
</style>

<input type="hidden" id="FileNm" value='@ViewBag.FileNm' />
<input type="hidden" id="SpName" value='@ViewBag.SpName' />
<input type="hidden" id="TypeNm" value='@ViewBag.TypeNm' />
<input type="hidden" id="Params" value='@ViewBag.Params' />

<body style="overflow: hidden;">

    <iframe id="iFrame" src="about://blank" frameborder="0"></iframe>

</body>


<script>

    function Consultar() {

        const _FileNm = document.getElementById("FileNm").value;

        const _SpName = document.getElementById("SpName").value;

        const _TypeNm = document.getElementById("TypeNm").value;

        const _Params = document.getElementById("Params").value;

        const _UrlDoc = `/rptViewer.aspx?FileNm=${_FileNm}&SpName=${_SpName}&TypeNm=${_TypeNm}&Params=${_Params}`;

        const _iFrame = document.getElementById("iFrame");

        _iFrame.onload = function () {
            _iFrame.contentDocument.body.style = "margin: 0px; overflow: hidden;";
            _iFrame.contentDocument.cookie = "";
        }

        _iFrame.src = _UrlDoc;

    };

    window.onload = function () {
        Consultar();
    }

</script>

WebAppSISGEFIN/Views/Reportes/_LayoutRpt.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Reporte</title>
    <link href="~/Riztie/Css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Riztie/Js/Design/jquery.min.js"></script>
    <script src="~/Riztie/Js/Design/sweetalert.min.js"></script>
    <script src="~/Riztie/Js/App/General.js"></script>
    <style>
        body {
            background-color: whitesmoke;
            overflow: hidden;
        }

        #iFrame {
            width: 100%;
            height: 85vh;
        }

        .marco {
            margin-top: 10px;
            padding: 8px !important;
            background-color: white !important;
        }

        .flex-gap {
            gap: 30px;
            display: flex;
            align-items: center;
        }


    </style>
</head>
<body>
    @RenderBody()
</body>
</html>

WebAppSISGEFIN/Views/Reportes/_PuenteRpt.cshtml
@{
    Layout = "_LayoutRpt.cshtml";
}

<style>
    #iFrame {
        position: absolute !important;
        left: 0px !important;
        top: 0px !important;
        width: 100% !important;
        height: 100vh !important;
        /*overflow: hidden;*/
    }
</style>

<input type="hidden" id="FileNm" value='@ViewBag.FileNm' />
<input type="hidden" id="SpName" value='@ViewBag.SpName' />
<input type="hidden" id="TypeNm" value='@ViewBag.TypeNm' />
<input type="hidden" id="Params" value='@ViewBag.Params' />
<input type="hidden" id="Option" value='@ViewBag.Option' />

<body style="overflow: hidden;">

    <iframe id="iFrame" src="about://blank" frameborder="0"></iframe>

</body>


<script>

    function Consultar() {

        const _FileNm = document.getElementById("FileNm").value;
        const _SpName = document.getElementById("SpName").value;
        const _TypeNm = document.getElementById("TypeNm").value;
        const _Params = document.getElementById("Params").value;
        const _Option = document.getElementById("Option").value;

        const _UrlDoc = `/rptViewer.aspx?FileNm=${_FileNm}&SpName=${_SpName}&TypeNm=${_TypeNm}&Params=${_Params}&r=${_Option}`;

        const _iFrame = document.getElementById("iFrame");

        _iFrame.onload = function () {
            _iFrame.contentDocument.body.style = "margin: 0px; overflow: hidden;";
            _iFrame.contentDocument.cookie = "";
        }

        _iFrame.src = _UrlDoc;

    };

    window.onload = function () {
        Consultar();
    }

</script>

WebAppSISGEFIN/Views/Reportes/rInventario1.cshtml
@{
    Layout = "_LayoutRpt.cshtml";
}

<input type="hidden" id="FileNm" value='@ViewBag.FileNm' />
<input type="hidden" id="SpName" value='@ViewBag.SpName' />
<input type="hidden" id="TypeNm" value='@ViewBag.TypeNm' />
<input type="hidden" id="Params" value='' />

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="flex-gap marco" >

                <div>
                    <span>Año</span>
                    <input type="number" id="txtEjecucion" onchange="ActualizarSel()" class="form-control form-control-sm" min="2000" max="2100" value="2022" />
                </div>

                <div>
                    <span>Oficinas</span>
                    <select id="cboOficinas" onchange="ActualizarSel()" class="form-control form-control-sm"></select>
                </div>

                <div>
                    <span>Ubicación</span>
                    <select id="cboUbicaciones" onchange="ActualizarSel()" class="form-control form-control-sm"></select>
                </div>

                <div>
                    <span>Responsable</span>
                    <input type="number" id="txtResponsable" onchange="ActualizarSel()" class="form-control form-control-sm" />
                </div>

                <div>
                    <span>Usuario</span>
                    <input type="number" id="txtUsuario" onchange="ActualizarSel()" class="form-control form-control-sm" />
                </div>

                <div>
                    <input type="button" class="btn btn-sm btn-primary" value="Consultar" onclick="ConsultarSel()" />
                </div>

            </div>             

            <div>
                <iframe id="iFrame" src="about://blank" frameborder="0"></iframe>
            </div>
            

        </div>
    </div>
</div>

<script>

    function ConsultarSel() {
        mostrarProgreso('Consultando..');

        const _iFrame = document.getElementById("iFrame");
        _iFrame.style.display = "none";

        const _FileNm = document.getElementById("FileNm").value;
        const _SpName = document.getElementById("SpName").value;
        const _TypeNm = document.getElementById("TypeNm").value;
        const _Params = document.getElementById("Params").value;
        const _UrlDoc = `/rptViewer.aspx?FileNm=${_FileNm}&SpName=${_SpName}&TypeNm=${_TypeNm}&Params=${_Params}`;

        _iFrame.onload = function () {
            _iFrame.contentDocument.body.style = "margin: 0px !Important; overflow:hidden !Important; ";
            _iFrame.contentDocument.cookie = "";
            _iFrame.style.display = "block";
            ocultarProgreso();
        }
        _iFrame.src = _UrlDoc;

    };

    function ActualizarSel() {
        const _txtEjecucio = document.getElementById('txtEjecucion');
        const _cboOficinas = document.getElementById('cboOficinas');
        const _cboUbicacns = document.getElementById('cboUbicaciones');
        const _txtRespons = document.getElementById('txtResponsable');
        const _txtUsuario  = document.getElementById('txtUsuario');
        const _Params = document.getElementById('Params');
        _Params.value = _txtEjecucio.value;
        _Params.value += '|' + _cboOficinas.value;
        _Params.value += '|' + _cboUbicacns.value;
        _Params.value += '|' + _txtRespons.value;
        _Params.value += '|' + _txtUsuario.value;
    }

    async function CargarCombo(nombre) {

        const _cboName = 'cbo' + nombre;
        const _actName = 'Get' + nombre;

        var _data = sessionStorage.getItem(_cboName);

        if (_data == null) {
            const _auxUrl = '@Url.Action("X","Reportes")';
            const _newUrl = _auxUrl.replace('X', _actName);
            const response = await fetch(_newUrl);
            _data = await response.text();
            sessionStorage.setItem(_cboName, _data);
        }

        var _lista = _data.split('¬');
        crearCombo(_lista, _cboName, "")

    }

    window.onload = function ()
    {
        CargarCombo('Oficinas');
        CargarCombo('Ubicaciones');
        ActualizarSel();
    }

</script>